apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec-probe
  labels:
    name: liveness-exec-probe
spec:
  containers:
  - name: liveness-exec-probe
    image: busybox:latest
    args:
      - /bin/sh
      - -c
      - touch /tmp/healthcheck; sleep 60; rm -rf /tmp/healthcheck; sleep 600
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthcheck
      initialDelaySeconds: 5
      periodSeconds: 5
