FROM python
WORKDIR /app
COPY . /app
CMD ["python", "app.py"]

# run the command
# docker build .
# docker run -it ImageId
# docker run -it e6100de0585d47b5efb3e8750488db9eabd9236a35a55524dc087aeb1ad46eb3