apiVersion: v1
kind: Pod
metadata:
  name: my-first-configmap-env
spec:
  containers:
  - name: my-first-container
    image: alpine
    command: ["sleep", "3600"]
    env:
      # define the env variable
      - name: PLAYER_INITIAL_LIVES # coming from configmap
        valueFrom:
          configMapKeyRef:
            name: my-first-configmap # coming from configmap
            key: player_initial_lives
      - name: UI_PROPERTIES_FILE_NAME # coming from configmap
        valueFrom:
          configMapKeyRef:
            name: my-first-configmap
            key: ui_properties_file_name
      - name: SECRET_NAME
        valueFrom:
          secretKeyRef:
            name: my-first-secret # coming from secret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-first-secret # coming from secret
            key: password
